[tool.ruff]
select = ["E", "F", "TCH", "SLF", "C4", "SIM", "B"]
ignore = [
    "E501",
]

[tool.pyright]
ignore = [
    "**/node_modules",
    "**/__pycache__",
    "**/migrations",
    ".git",
    "./venv",
]
exclude = [
    "**/node_modules",
    "**/__pycache__",
    "**/migrations",
    ".git",
    "./venv",
]